name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Convert repo owner to lowercase
        id: lower_owner
        run: echo "REPO_OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker image with cache
        run: |
          docker buildx build \
            --push \
            --tag ghcr.io/${{ env.REPO_OWNER_LOWER }}/javaapp:1.0.0 \
            --tag ghcr.io/${{ env.REPO_OWNER_LOWER }}/javaapp:latest \
            # --cache-from=type=registry,ref=ghcr.io/${{ env.REPO_OWNER_LOWER }}/javaapp:cache \
            # --cache-to=type=registry,ref=ghcr.io/${{ env.REPO_OWNER_LOWER }}/javaapp:cache,mode=max \
            .

